/**
 * API client for the install/setup catalog.
 *
 * The catalog (install/catalog.toml on the server) is the single source
 * of truth for deployment labels/descriptions, install-mode labels,
 * per-install-mode service-mode visibility rules, and the prompts
 * shown for the `custom` deployment's advanced fields. Both the install
 * scripts (via the generated _catalog.sh / _catalog.ps1) and the
 * Setup Wizard (via this endpoint) share it.
 *
 * A JSON snapshot of the same data is also bundled into the SPA at
 * build time (see `installCatalogData.json`, generated by
 * `install/scripts/build_catalog.py`). The bundled copy is what the
 * Electron installer stage uses — that stage runs before any backend
 * exists, so the API endpoint is unreachable. The runtime endpoint is
 * still preferred when available because it also returns the active
 * install mode from `INSTALL_MODE`.
 */

// The bundled JSON is regenerated whenever install/catalog.toml changes
// (CI's `python install/scripts/build_catalog.py --check` fails on drift).
// Import-with-default lets Vite inline the file into the bundle.
import bundledCatalogRaw from './installCatalogData.json';

function resolveBaseUrl(agentUrl: string): string {
  if (agentUrl.startsWith('http://') || agentUrl.startsWith('https://')) {
    return agentUrl;
  }
  return `${window.location.origin}${agentUrl}`;
}

export type ServiceMode = 'docker' | 'native' | 'external';

export interface DeploymentAdvancedField {
  key: string;
  prompt: string;
  hint: string;
  default: string;
  choices?: string[];
}

export interface DeploymentEntry {
  label: string;
  short?: string;
  description: string;
  env_value: string;
  host?: string;
  requires_host?: boolean;
  order?: number;
  advanced_fields?: DeploymentAdvancedField[];
}

export interface InstallModeEntry {
  label: string;
  description: string;
  hint?: string;
  badge?: string;
  requires?: string[];
  order?: number;
}

export interface ModeRule {
  allowed_service_modes: ServiceMode[];
  default_service_mode: ServiceMode | '';
}

export interface ServiceModeEntry {
  label: string;
  description_template: string;
}

export interface InstallCatalog {
  schema_version?: number;
  deployments: Record<string, DeploymentEntry>;
  modes: Record<string, InstallModeEntry>;
  mode_rules: Record<string, ModeRule>;
  service_modes: Record<string, ServiceModeEntry>;
}

export interface InstallCatalogResponse {
  catalog: InstallCatalog;
  /** INSTALL_MODE from the rendered .env; null when unset or unknown. */
  active_install_mode: string | null;
}

export async function fetchInstallCatalog(agentUrl: string): Promise<InstallCatalogResponse> {
  const base = resolveBaseUrl(agentUrl);
  const res = await fetch(`${base}/api/config/install-catalog`);
  if (!res.ok) throw new Error(`Failed to fetch install catalog: ${res.statusText}`);
  return res.json();
}

/**
 * The catalog snapshot inlined into the SPA bundle at build time. The
 * `_meta` key the generator stamps in is dropped so the shape matches
 * `InstallCatalogResponse.catalog`. Use this when the backend isn't
 * reachable yet (the Electron installer stage, before `openpa serve`
 * starts).
 */
export function getBundledInstallCatalog(): InstallCatalog {
  // `_meta` carries the SHA-256 + schema version for the CI drift check;
  // it isn't part of the public catalog shape, so strip it before
  // handing back.
  const { _meta: _meta, ...catalog } = bundledCatalogRaw as InstallCatalog & {
    _meta?: unknown;
  };
  void _meta;
  return catalog;
}

/**
 * Render a service-mode description by substituting the service's
 * display name into the catalog's template. Mirrors the backend's
 * intent (template stays a single string in TOML, not a JS function).
 */
export function renderServiceModeDescription(
  entry: ServiceModeEntry,
  serviceName: string,
): string {
  return entry.description_template.split('{service}').join(serviceName);
}

/**
 * Capabilities probed by the installer/Electron-bridge — used by
 * ``recommendInstallMode`` to decide which modes are usable in the
 * current environment. Add new capability flags here as new
 * ``modes.<id>.requires`` strings appear in the catalog.
 */
export interface InstallEnvCapabilities {
  /** ``docker info`` succeeded — Docker daemon is reachable. */
  hasDocker: boolean;
}

/**
 * Pick the recommended install mode from the catalog. Walks the
 * ``modes`` table in ``order`` ascending and returns the first mode
 * whose ``requires`` capabilities are all satisfied. Returns ``null``
 * when no mode qualifies (which today never happens: ``native``
 * declares no requirements). The same algorithm is used by install.sh
 * and install.ps1, where it falls out implicitly from "Choice [1] =
 * first MODE_ID = lowest order in the generated _catalog.sh / .ps1".
 */
export function recommendInstallMode(
  catalog: InstallCatalog | null | undefined,
  caps: InstallEnvCapabilities,
): string | null {
  if (!catalog) return null;
  const modes = Object.entries(catalog.modes).sort(
    (a, b) => (a[1].order ?? 999) - (b[1].order ?? 999),
  );
  for (const [id, entry] of modes) {
    const requires = entry.requires ?? [];
    const satisfied = requires.every((req) => {
      if (req === 'docker') return caps.hasDocker;
      // Unknown requirement → conservatively treat as unsatisfied so a
      // typo in catalog.toml doesn't silently advertise an unsupported
      // mode. Add new branches above as new capabilities appear.
      return false;
    });
    if (satisfied) return id;
  }
  return null;
}
