# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import me5_embedding_pb2 as me5__embedding__pb2


class ME5EmbeddingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSentenceEmbeddingsMe5Large = channel.unary_unary(
            "/me5embedding.ME5EmbeddingService/GetSentenceEmbeddingsMe5Large",
            request_serializer=me5__embedding__pb2.EmbeddingRequest.SerializeToString,
            response_deserializer=me5__embedding__pb2.EmbeddingResponse.FromString,
        )
        self.GetSentenceEmbeddingsMe5Small = channel.unary_unary(
            "/me5embedding.ME5EmbeddingService/GetSentenceEmbeddingsMe5Small",
            request_serializer=me5__embedding__pb2.EmbeddingRequest.SerializeToString,
            response_deserializer=me5__embedding__pb2.EmbeddingResponse.FromString,
        )


class ME5EmbeddingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSentenceEmbeddingsMe5Large(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSentenceEmbeddingsMe5Small(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ME5EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSentenceEmbeddingsMe5Large": grpc.unary_unary_rpc_method_handler(
            servicer.GetSentenceEmbeddingsMe5Large,
            request_deserializer=me5__embedding__pb2.EmbeddingRequest.FromString,
            response_serializer=me5__embedding__pb2.EmbeddingResponse.SerializeToString,
        ),
        "GetSentenceEmbeddingsMe5Small": grpc.unary_unary_rpc_method_handler(
            servicer.GetSentenceEmbeddingsMe5Small,
            request_deserializer=me5__embedding__pb2.EmbeddingRequest.FromString,
            response_serializer=me5__embedding__pb2.EmbeddingResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "me5embedding.ME5EmbeddingService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ME5EmbeddingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSentenceEmbeddingsMe5Large(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/me5embedding.ME5EmbeddingService/GetSentenceEmbeddingsMe5Large",
            me5__embedding__pb2.EmbeddingRequest.SerializeToString,
            me5__embedding__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetSentenceEmbeddingsMe5Small(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/me5embedding.ME5EmbeddingService/GetSentenceEmbeddingsMe5Small",
            me5__embedding__pb2.EmbeddingRequest.SerializeToString,
            me5__embedding__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
