# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: me5_embedding.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13me5_embedding.proto\x12\x0cme5embedding\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"0\n\x11\x45mbeddingResponse\x12\x1b\n\x13sentence_embeddings\x18\x01 \x03(\x02\x32\xd9\x01\n\x13ME5EmbeddingService\x12`\n\x1dGetSentenceEmbeddingsMe5Large\x12\x1e.me5embedding.EmbeddingRequest\x1a\x1f.me5embedding.EmbeddingResponse\x12`\n\x1dGetSentenceEmbeddingsMe5Small\x12\x1e.me5embedding.EmbeddingRequest\x1a\x1f.me5embedding.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'me5_embedding_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=37
  _globals['_EMBEDDINGREQUEST']._serialized_end=69
  _globals['_EMBEDDINGRESPONSE']._serialized_start=71
  _globals['_EMBEDDINGRESPONSE']._serialized_end=119
  _globals['_ME5EMBEDDINGSERVICE']._serialized_start=122
  _globals['_ME5EMBEDDINGSERVICE']._serialized_end=339
# @@protoc_insertion_point(module_scope)
